# Generated by Django 2.2.6 on 2019-11-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.CharField(max_length=30)),
                ('userid', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('blogtext', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
